### ISSUE TITLE
Wrong checkbox position in horizontal form

### ISSUE THREAD

**Issue by woto** [rafaelfranca/simple_form-bootstrap#51]
Hi, i found that removing in this line https://github.com/rafaelfranca/simple_form-bootstrap/blob/master/config/initializers/simple_form_bootstrap.rb#L90 ".col-sm-9" lead to correct position.

For now this "bug"? also visible in http://simple-form-bootstrap.plataformatec.com.br/ in "Simple Form: Horizontal Form" panel

**Comment by jfragoulis** [comment]
Add the following rule:

```css
.form-horizontal .checkbox input[type=checkbox] {
  width: auto;
}
```
